/oak_d_pro:
    camera_i_pipeline_type: Stereo
    camera_i_enable_ir: false  
    camera_i_enable_imu: false
    camera_i_nn_type: none
    camera_i_mx_id: '194430101134992E00'
    camera_i_usb_speed: SUPER_PLUS
    left_i_resolution: '400P'
    left_i_fps: 30
    right_i_resolution: '400P'
    right_i_fps: 30
    # rgb_i_resolution: '720P'
    # rgb_i_fps: 30  
/oak_mono_triple:
    camera_i_pipeline_type: CamArray
    camera_i_enable_imu: false
    camera_i_enable_ir: false
    camera_i_nn_type: none  
    camera_i_mx_id: '14442C10A1A79ED200'
    camera_i_usb_speed: SUPER_PLUS    
    left_i_resolution: '400P'
    left_i_fps: 30
    right_i_resolution: '400P'
    right_i_fps: 30
    # cam_d_i_resolution: '400P'
    # cam_d_i_fps: 30